### ISSUE TITLE
Readme formatting error on Package Control.  

### ISSUE THREAD

**Issue by TheBaronHimself** [TheBaronHimself/Spaceblack#9]
Hey Saad, 

The formatting of the Readme file on Package Control isn't displayed correctly.
Have a look:

<img width="427" alt="formatting-issue" src="https://cloud.githubusercontent.com/assets/11179011/9056168/f3ab84aa-3a88-11e5-9904-2c9ea177af01.png">

Take care, 
Simon-Claudius

**Comment by saadq** [comment]
Hi Simon-Claudius,

I'm not sure why this is happening if there is no issue with the README in the GitHub repo, which is where Package Control gets the info for the README. I'll look into it.

**Comment by TheBaronHimself** [comment]
Fixed. I added another line break, which did the trick.
